### ISSUE TITLE
Install vs Uninstall *skill*

### ISSUE THREAD

**Issue by valdr** [MycroftAI/skill-installer#10]
I was wondering why installing does not require the vocabulary "skill", where uninstalling does.
Are there other parts of Mycroft we are able to uninstall with a voice command? "Hey Mycroft, uninstall core"?

**Comment by MatthewScholefield** [comment]
I think we had this because with the word `remove`, there's also things like `remove alarm`. So, we could change it to:
```
remove skill
uninstall
```
Does this sound better?

**Comment by penrods** [comment]
I intentionally made it a little difficult to prevent accidental uninstalls.  We did just add a confirmation stage, so maybe this is unnecessary.  But I am also nervous about single-word intents -- the chance of vocabulary conflict is really high.

**Comment by MatthewScholefield** [comment]
Closing since this has been fixed with the rework. Using Padatious, single word intents have much less conflicts.
