### ISSUE TITLE
py_msm

### ISSUE THREAD

**Issue by JarbasAI** [MycroftAI/skill-installer#23]
what about migrating this to the new py_msm package?

i would be more than happy to make any needed changes to the package itself if needed, this is the exact use case i have for it

instead of making my own skill i wanted your opinion about this

**Comment by forslund** [comment]
Looks neat! Going to try it out and see how it works.

There have been talk of rewriting the current msm in python (so thismight save a lot of work).

@penrods, @LearnedVector and @MatthewScholefield should probably say theirs about this as well.

**Comment by forslund** [comment]
Link the the module: https://github.com/JarbasAl/py_msm

**Comment by MatthewScholefield** [comment]
This has been merged. Thanks again!
