### ISSUE TITLE
Skill not load (ValueError: too many values to unpack (expected 2))

### ISSUE THREAD

**Issue by gras64** [MycroftAI/skill-installer#30]
I have the following message on my devices for several days. whether Raspberry pi or Ubuntu Desktop can no longer install skills. my systems used core version 18.2.9 i have no idea what to do

01:47:17.661 - SkillInstallerSkill - INFO - Installer Skill web settings have changed
01:47:17.661 - mycroft.skills.core:load_skill:144 - ERROR - Failed to load skill: mycroft-installer.mycroftai
Traceback (most recent call last):
File "/home/pi/mycroft-core/mycroft/skills/core.py", line 127, in load_skill
skill.initialize()
File "/opt/mycroft/skills/mycroft-installer.mycroftai/__init__.py", line 36, in initialize
self.install_word, self.remove_word = self.translate_list('action')
ValueError: too many values to unpack (expected 2)

**Comment by forslund** [comment]
Hi @gras64 are you running any translation modifications that you're working on?

The row that errors expects that the `/dialog/LANG/action.list` contains exactly 2 rows. A first check I'd like you to do is see if that file looks alright.

**Comment by gras64** [comment]
thank you for your time.
I use the German translation from the repository. Under the Old Python version, the translation actually worked. I have only two values ​​in the dialogue file.

**Comment by penrods** [comment]
Is this still an issue?

**Comment by gras64** [comment]
yes just checked again. Unfortunately no solution found yet

22:42:42.997 - mycroft.skills.core:load_skill:152 - ERROR - Failed to load skill: skill-installer
Traceback (most recent call last):
File "/home/osmc/mycroft-core/mycroft/skills/core.py", line 136, in load_skill
raise e
File "/home/osmc/mycroft-core/mycroft/skills/core.py", line 132, in load_skill
skill.initialize()
File "/opt/mycroft/skills/skill-installer/__init__.py", line 40, in initialize
self.install_word, self.remove_word = self.translate_list('action')
ValueError: too many values to unpack (expected 2)

**Comment by forslund** [comment]
I did a quick debug session and it seems like for some reason the file actions.list contains an invisible `\n` after the last word and I can't get it to go away.

**Comment by forslund** [comment]
Ok I found a way to remove the trailing EOL's...a bit tricky...

**Comment by gras64** [comment]
no idea where the line break came from and why I can not delete that mostly use "Nano"

**Comment by forslund** [comment]
I had to set vim to binary mode and set the noeol option and then save the file... Weird stuff.
