### ISSUE TITLE
Feature Request: Query installed skills

### ISSUE THREAD

**Issue by spagy** [MycroftAI/skill-installer#37]
It would be nice to be able to ask things such as
"Is Spotify installed?"

**Comment by spagy** [comment]
I'd be happy to have a go at this one myself, I haven't really got any experience but it seems like it *shouldn't* be too difficult

**Comment by MatthewScholefield** [comment]
@spagy Thanks, yeah I think this would be a perfect first task to tackle since it shouldn't be too hard. Of course, don't hesitate to ask on Mattermost if you run into anything.

**Comment by forslund** [comment]
Closing this since PR #38 has been merged.
