### ISSUE TITLE
Responds, but nothing is installed

### ISSUE THREAD

**Issue by singpolyma** [MycroftAI/skill-installer#5]
On my Mark1, when I say `install ping` Mycoft says `Installing...` but then nothing seems to happen (looking at `ps faux` I don't see anything, and looking in the skills directory nothing appears).

**Comment by singpolyma** [comment]
Nevermind. It did work.  Probably should say "done installing" or something so it feels like it's working

**Comment by singpolyma** [comment]
Ok... not sure how it worked that one time... now I've found the log file it's complaining that `locate` is not installed on the mark1.  It wants locate because it think it's not on a "pycroft" setup (though the mark1 *is* a pi...)

**Comment by penrods** [comment]
I believe this is all cleared up now.  Reopen if this is still a problem for you.
