### ISSUE TITLE
Missing build_msm_config

### ISSUE THREAD

**Issue by neopablo2000** [MycroftAI/skill-installer#56]
When loading, this message shows app in debug (sorry for my English, i`m from Argentina). 

` File "/opt/mycroft/skills/skill-installer/__init__.py", line 34, in <module>
    from mycroft.skills.msm_wrapper import build_msm_config, create_msm
ImportError: cannot import name 'build_msm_config' `

It looks like build_msm_config is not defined in msm_wrapper.py, as i can confirm by opening that file and reading code. Hope it helps!! Thank you!

Ubuntu Mate 18.04
Mycroft by Git, stable branch

**Comment by krisgesling** [comment]
Hi there,

It looks like your device is running the 19.08 release of the Installer Skill but on the 19.02 (stable/master) branch of Mycroft-core. Did you manually install this?

The good news is that we are releasing 19.08 shortly so if you allow the update this should all resolve on its own :)

**Comment by neopablo2000** [comment]
Wow, those are really good news!!! Ok, waiting!! I`ll close this thread so! Thank you for your fast answer!
